### ISSUE TITLE
Testing convoluntional layer

### ISSUE THREAD

**Issue by Kozon2015** [CSTR-Edinburgh/mlpractical#98]
In notebooks/ConvolutionalLayer_tests.ipynb ，I tested the mlp.layers.ConvolutionalLayer ,but it has some problems, both fprop and bprop can't get correct output

**Comment by AntreasAntoniou** [comment]
That's because your implementation is incorrect. Or you are using the wrong testing flags. Also, you should post on piazza and not on the GitHub page.
