### ISSUE TITLE
algorithm.sty and algorithmic.sty missing in report in branch coursework_2

### ISSUE THREAD

**Issue by fhennig** [CSTR-Edinburgh/mlpractical#99]
Hi,

Just fyi the `main.tex` in report doesn't compile because of the missing style files. Copying them from the `coursework_1` branch fixes the issue.

**Comment by AntreasAntoniou** [comment]
It definitely compiled when I used these on overleaf.  Algorithm and algorithmic are well-known packages that your local setup was missing.

**Comment by fhennig** [comment]
Alright! I thought since they were provided on the coursework_1 branch that they were some special modified packages. If it's just default packages I know where to find them, thanks!
